w=set()
s=int(input("enter no 1: "))
w.add(s)
s=int(input("enter no 2: "))
w.add(s)
s=int(input("enter no 3: "))
w.add(s)
s=int(input("enter no 4: "))
w.add(s)
s=int(input("enter no 5: "))
w.add(s)
s=int(input("enter no 6: "))
w.add(s)
s=int(input("enter no 7: "))
w.add(s)
s=int(input("enter no 8: "))
w.add(s)
print(w)