d={}
name=input("enter 1 friend name  ")
lang=input("enter there language ")
d.update({name:lang})
name=input("enter 2 friend name  ")
lang=input("enter there language ")
d.update({name:lang})
name=input("enter 3 friend name  ")
lang=input("enter there language ")
d.update({name:lang})
name=input("enter 4 friend name  ")
lang=input("enter there language ")
d.update({name:lang})
print(d)