student=[]
s1 =input("1st marks: ")
student.append(s1)
s2 =input("2st marks: ")
student.append(s2)
s3 =input("3st marks: ")
student.append(s3)
s4 =input("4st marks: ")
student.append(s4)
s5 =input("5st marks: ")
student.append(s5)
s6 =input("6st marks: ")
student.append(s6)
student.sort()
print(student)